version: '3.9'

services:
  app_server:
    container_name: app_server
    image: app_server:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file: ./src/common/envs/development.env
    environment:
      - DATABASE_URL="postgresql://postgres:123@192.168.200.209:5432/lcmarket?schema=public"
    ports:
      - '3000:3000'
      - '48525:48525'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/api/v1/health || exit 1
      interval: 3600s
      retries: 5
      start_period: 20s
      timeout: 10s
